name: CodeClimate
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: f7b0096a1ea5a02b50e256bc2ae54941a6ef4c1d73ef1bc33243b9670f8fd69a
        with:
          coverageCommand: yarn test:coverage
          debug: true
